library(rearrr)
context("min_max_scale()")


test_that("min_max_scale()", {
  xpectr::set_test_seed(42)

  vec <- runif(10, min = -4, max = 3)

  # Generate expectations for 'min_max_scale'
  # Tip: comment out the gxs_function() call
  # so it is easy to regenerate the tests
  xpectr::set_test_seed(42)
  # xpectr::gxs_function(
  #   fn = min_max_scale,
  #   args_values = list(
  #     "x" = list(vec, "hej", c(vec, NA)),
  #     "new_min" = list(0, 5, NA),
  #     "new_max" = list(1, 6, NA),
  #     "old_min" = list(NULL, -5, NA),
  #     "old_max" = list(NULL, 6, NA),
  #     "na.rm" = list(TRUE, FALSE)
  #   ),extra_combinations = list(
  #     list("x" = c(vec, NA), "na.rm" = FALSE)
  #   ),
  #   indentation = 2
  # )


  ## Testing 'min_max_scale'                                                  ####
  ## Initially generated by xpectr
  # Testing different combinations of argument values

  # Testing min_max_scale(x = vec, new_min = 0, new_max ...
  xpectr::set_test_seed(42)
  # Assigning output
  output_19148 <- min_max_scale(x = vec, new_min = 0, new_max = 1, old_min = NULL, old_max = NULL, na.rm = TRUE)
  # Testing class
  expect_equal(
    class(output_19148),
    "numeric",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_19148,
    type = "double")
  # Testing values
  expect_equal(
    output_19148,
    c(0.97225, 1, 0.18877, 0.86712, 0.63195, 0.47909, 0.75014, 0, 0.65095,
      0.71086),
    tolerance = 1e-4)
  # Testing names
  expect_equal(
    names(output_19148),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_19148),
    10L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_19148)),
    10L)

  # Testing min_max_scale(x = "hej", new_min = 0, new_ma...
  # Changed from baseline: x = "hej"
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19370 <- xpectr::capture_side_effects(min_max_scale(x = "hej", new_min = 0, new_max = 1, old_min = NULL, old_max = NULL, na.rm = TRUE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19370[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'x': Must be of type 'numeric', not 'character'."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19370[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing min_max_scale(x = c(vec, NA), new_min = 0, n...
  # Changed from baseline: x = c(vec, NA)
  xpectr::set_test_seed(42)
  # Assigning output
  output_12861 <- min_max_scale(x = c(vec, NA), new_min = 0, new_max = 1, old_min = NULL, old_max = NULL, na.rm = TRUE)
  # Testing class
  expect_equal(
    class(output_12861),
    "numeric",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_12861,
    type = "double")
  # Testing values
  expect_equal(
    output_12861,
    c(0.97225, 1, 0.18877, 0.86712, 0.63195, 0.47909, 0.75014, 0, 0.65095,
      0.71086, NA),
    tolerance = 1e-4)
  # Testing names
  expect_equal(
    names(output_12861),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_12861),
    11L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_12861)),
    11L)

  # Testing min_max_scale(x = NULL, new_min = 0, new_max...
  # Changed from baseline: x = NULL
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_18304 <- xpectr::capture_side_effects(min_max_scale(x = NULL, new_min = 0, new_max = 1, old_min = NULL, old_max = NULL, na.rm = TRUE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_18304[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'x': Must be of type 'numeric', not 'NULL'."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_18304[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing min_max_scale(x = c(vec, NA), new_min = 0, n...
  # Changed from baseline: x, na.rm
  xpectr::set_test_seed(42)
  # Assigning output
  output_16417 <- min_max_scale(x = c(vec, NA), new_min = 0, new_max = 1, old_min = NULL, old_max = NULL, na.rm = FALSE)
  # Testing class
  expect_equal(
    class(output_16417),
    "numeric",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_16417,
    type = "double")
  # Testing values
  expect_equal(
    output_16417,
    c(NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_,
      NA_real_, NA_real_, NA_real_, NA_real_),
    tolerance = 1e-4)
  # Testing names
  expect_equal(
    names(output_16417),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_16417),
    11L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_16417)),
    11L)

  # Testing min_max_scale(x = vec, new_min = 5, new_max ...
  # Changed from baseline: new_min = 5
  xpectr::set_test_seed(42)
  # Assigning output
  output_15190 <- min_max_scale(x = vec, new_min = 5, new_max = 1, old_min = NULL, old_max = NULL, na.rm = TRUE)
  # Testing class
  expect_equal(
    class(output_15190),
    "numeric",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_15190,
    type = "double")
  # Testing values
  expect_equal(
    output_15190,
    c(1.11101, 1, 4.24491, 1.53154, 2.47222, 3.08362, 1.99943, 5, 2.39621,
      2.15657),
    tolerance = 1e-4)
  # Testing names
  expect_equal(
    names(output_15190),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_15190),
    10L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_15190)),
    10L)

  # Testing min_max_scale(x = vec, new_min = NA, new_max...
  # Changed from baseline: new_min = NA
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_17365 <- xpectr::capture_side_effects(min_max_scale(x = vec, new_min = NA, new_max = 1, old_min = NULL, old_max = NULL, na.rm = TRUE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_17365[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'new_min': May not be NA."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_17365[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing min_max_scale(x = vec, new_min = NULL, new_m...
  # Changed from baseline: new_min = NULL
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_11346 <- xpectr::capture_side_effects(min_max_scale(x = vec, new_min = NULL, new_max = 1, old_min = NULL, old_max = NULL, na.rm = TRUE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_11346[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'new_min': Must be of type 'number', not 'NULL'."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_11346[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing min_max_scale(x = vec, new_min = 0, new_max ...
  # Changed from baseline: new_max = 6
  xpectr::set_test_seed(42)
  # Assigning output
  output_16569 <- min_max_scale(x = vec, new_min = 0, new_max = 6, old_min = NULL, old_max = NULL, na.rm = TRUE)
  # Testing class
  expect_equal(
    class(output_16569),
    "numeric",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_16569,
    type = "double")
  # Testing values
  expect_equal(
    output_16569,
    c(5.83348, 6, 1.13264, 5.20269, 3.79168, 2.87456, 4.50086, 0, 3.90568,
      4.26514),
    tolerance = 1e-4)
  # Testing names
  expect_equal(
    names(output_16569),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_16569),
    10L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_16569)),
    10L)

  # Testing min_max_scale(x = vec, new_min = 0, new_max ...
  # Changed from baseline: new_max = NA
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_17050 <- xpectr::capture_side_effects(min_max_scale(x = vec, new_min = 0, new_max = NA, old_min = NULL, old_max = NULL, na.rm = TRUE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_17050[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'new_max': May not be NA."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_17050[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing min_max_scale(x = vec, new_min = 0, new_max ...
  # Changed from baseline: new_max = NULL
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_14577 <- xpectr::capture_side_effects(min_max_scale(x = vec, new_min = 0, new_max = NULL, old_min = NULL, old_max = NULL, na.rm = TRUE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_14577[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'new_max': Must be of type 'number', not 'NULL'."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_14577[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing min_max_scale(x = vec, new_min = 0, new_max ...
  # Changed from baseline: old_min = -5
  xpectr::set_test_seed(42)
  # Assigning output
  output_17191 <- min_max_scale(x = vec, new_min = 0, new_max = 1, old_min = -5, old_max = NULL, na.rm = TRUE)
  # Testing class
  expect_equal(
    class(output_17191),
    "numeric",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_17191,
    type = "double")
  # Testing values
  expect_equal(
    output_17191,
    c(0.97938, 1, 0.39724, 0.90126, 0.72653, 0.61296, 0.81435, 0.25698,
      0.74065, 0.78516),
    tolerance = 1e-4)
  # Testing names
  expect_equal(
    names(output_17191),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_17191),
    10L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_17191)),
    10L)

  # Testing min_max_scale(x = vec, new_min = 0, new_max ...
  # Changed from baseline: old_min = NA
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19346 <- xpectr::capture_side_effects(min_max_scale(x = vec, new_min = 0, new_max = 1, old_min = NA, old_max = NULL, na.rm = TRUE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19346[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'old_min': May not be NA."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19346[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing min_max_scale(x = vec, new_min = 0, new_max ...
  # Changed from baseline: old_max = NA
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_12554 <- xpectr::capture_side_effects(min_max_scale(x = vec, new_min = 0, new_max = 1, old_min = NULL, old_max = NA, na.rm = TRUE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_12554[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'old_max': May not be NA."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_12554[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing min_max_scale(x = vec, new_min = 0, new_max ...
  # Changed from baseline: old_max = 6
  xpectr::set_test_seed(42)
  # Assigning output
  output_14622 <- min_max_scale(x = vec, new_min = 0, new_max = 1, old_min = NULL, old_max = 6, na.rm = TRUE)
  # Testing class
  expect_equal(
    class(output_14622),
    "numeric",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_14622,
    type = "double")
  # Testing values
  expect_equal(
    output_14622,
    c(0.60293, 0.62015, 0.11707, 0.53774, 0.3919, 0.29711, 0.4652, 0,
      0.40368, 0.44083),
    tolerance = 1e-4)
  # Testing names
  expect_equal(
    names(output_14622),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_14622),
    10L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_14622)),
    10L)

  # Testing min_max_scale(x = vec, new_min = 0, new_max ...
  # Changed from baseline: na.rm = FALSE
  xpectr::set_test_seed(42)
  # Assigning output
  output_19400 <- min_max_scale(x = vec, new_min = 0, new_max = 1, old_min = NULL, old_max = NULL, na.rm = FALSE)
  # Testing class
  expect_equal(
    class(output_19400),
    "numeric",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_19400,
    type = "double")
  # Testing values
  expect_equal(
    output_19400,
    c(0.97225, 1, 0.18877, 0.86712, 0.63195, 0.47909, 0.75014, 0, 0.65095,
      0.71086),
    tolerance = 1e-4)
  # Testing names
  expect_equal(
    names(output_19400),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_19400),
    10L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_19400)),
    10L)

  # Testing min_max_scale(x = vec, new_min = 0, new_max ...
  # Changed from baseline: na.rm = NULL
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19782 <- xpectr::capture_side_effects(min_max_scale(x = vec, new_min = 0, new_max = 1, old_min = NULL, old_max = NULL, na.rm = NULL), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19782[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'na.rm': Must be of type 'logical flag', not 'NULL'."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19782[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  ## Finished testing 'min_max_scale'                                         ####
  #


})
