library(rearrr)
context("closest_to(), furthest_from()")


test_that("fuzz testing closest_to()", {
  xpectr::set_test_seed(42)

  # Create a data frame
  df_length <- 6
  df <- data.frame(
    "index" = 1:df_length,
    "A" = sample(1:df_length),
    "B" = runif(df_length),
    "C" = LETTERS[1:df_length],
    "G" = rep(c(1, 2), each = df_length/2),
    "G_index" = rep(1:(df_length/2), times = 2),
    stringsAsFactors = FALSE
  )

  # Generate expectations for 'closest_to'
  # Tip: comment out the gxs_function() call
  # so it is easy to regenerate the tests
  xpectr::set_test_seed(42)
  # xpectr::gxs_function(
  #   fn = closest_to,
  #   args_values = list(
  #     "data" = list(df, dplyr::group_by(df, G), 1:10, -3:3, NA),
  #     "col" = list(NULL, "A", "B", "C"),
  #     "origin" = list(2, 10, NA, factor(c(1))),
  #     "origin_fn" = list(NULL),
  #     "shuffle_ties" = list(FALSE, TRUE)
  #   ),
  #   extra_combinations = list(
  #     list("origin" = NULL, "origin_fn" = create_origin_fn(median)),
  #     list("origin" = NULL, "origin_fn" = create_origin_fn(max)),
  #     list("origin" = NULL, "origin_fn" = create_origin_fn(identity))
  #   ),
  #   indentation = 2
  # )


  ## Testing 'closest_to'                                                     ####
  ## Initially generated by xpectr
  # Testing different combinations of argument values

  # Testing closest_to(data = df, col = NULL, origin = 2...
  xpectr::set_test_seed(42)
  # Assigning output
  output_19148 <- closest_to(data = df, col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_19148),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_19148[["index"]],
    c(2, 1, 3, 4, 5, 6),
    tolerance = 1e-4)
  expect_equal(
    output_19148[["A"]],
    c(5, 6, 2, 3, 4, 1),
    tolerance = 1e-4)
  expect_equal(
    output_19148[["B"]],
    c(0.13467, 0.73659, 0.65699, 0.70506, 0.45774, 0.71911),
    tolerance = 1e-4)
  expect_equal(
    output_19148[["C"]],
    c("B", "A", "C", "D", "E", "F"),
    fixed = TRUE)
  expect_equal(
    output_19148[["G"]],
    c(1, 1, 1, 2, 2, 2),
    tolerance = 1e-4)
  expect_equal(
    output_19148[["G_index"]],
    c(2, 1, 3, 1, 2, 3),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_19148),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_19148),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_19148),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_19148),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_19148)),
    character(0),
    fixed = TRUE)

  # Testing closest_to(data = dplyr::group_by(df, G), co...
  # Changed from baseline: data = dplyr::group_b...
  xpectr::set_test_seed(42)
  # Assigning output
  output_19370 <- closest_to(data = dplyr::group_by(df, G), col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_19370),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_19370[["index"]],
    c(2, 1, 3, 5, 4, 6),
    tolerance = 1e-4)
  expect_equal(
    output_19370[["A"]],
    c(5, 6, 2, 4, 3, 1),
    tolerance = 1e-4)
  expect_equal(
    output_19370[["B"]],
    c(0.13467, 0.73659, 0.65699, 0.45774, 0.70506, 0.71911),
    tolerance = 1e-4)
  expect_equal(
    output_19370[["C"]],
    c("B", "A", "C", "E", "D", "F"),
    fixed = TRUE)
  expect_equal(
    output_19370[["G"]],
    c(1, 1, 1, 2, 2, 2),
    tolerance = 1e-4)
  expect_equal(
    output_19370[["G_index"]],
    c(2, 1, 3, 2, 1, 3),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_19370),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_19370),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_19370),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_19370),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_19370)),
    character(0),
    fixed = TRUE)

  # Testing closest_to(data = 1:10, col = NULL, origin =...
  # Changed from baseline: data = 1:10
  xpectr::set_test_seed(42)
  # Assigning output
  output_12861 <- closest_to(data = 1:10, col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_12861),
    "integer",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_12861,
    type = "integer")
  # Testing values
  expect_equal(
    output_12861,
    c(2, 1, 3, 4, 5, 6, 7, 8, 9, 10),
    tolerance = 1e-4)
  # Testing names
  expect_equal(
    names(output_12861),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_12861),
    10L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_12861)),
    10L)

  # Testing closest_to(data = -3:3, col = NULL, origin =...
  # Changed from baseline: data = -3:3
  xpectr::set_test_seed(42)
  # Assigning output
  output_18304 <- closest_to(data = -3:3, col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_18304),
    "integer",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_18304,
    type = "integer")
  # Testing values
  expect_equal(
    output_18304,
    c(2, 1, 3, 0, -1, -2, -3),
    tolerance = 1e-4)
  # Testing names
  expect_equal(
    names(output_18304),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_18304),
    7L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_18304)),
    7L)

  # Testing closest_to(data = NA, col = NULL, origin = 2...
  # Changed from baseline: data = NA
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_16417 <- xpectr::capture_side_effects(closest_to(data = NA, col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = FALSE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_16417[['error']]),
    xpectr::strip("Assertion failed. One of the following must apply:\n * checkmate::check_data_frame(data): Must be of type 'data.frame', not 'logical'\n * checkmate::check_vector(data): Contains missing values (element 1)\n * checkmate::check_factor(data): Contains missing values (element 1)"),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_16417[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing closest_to(data = NULL, col = NULL, origin =...
  # Changed from baseline: data = NULL
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_15190 <- xpectr::capture_side_effects(closest_to(data = NULL, col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = FALSE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_15190[['error']]),
    xpectr::strip("Assertion failed. One of the following must apply:\n * checkmate::check_data_frame(data): Must be of type 'data.frame', not 'NULL'\n * checkmate::check_vector(data): Must be of type 'vector', not 'NULL'\n * checkmate::check_factor(data): Must be of type 'factor', not 'NULL'"),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_15190[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing closest_to(data = df, col = "A", origin = 2,...
  # Changed from baseline: col = "A"
  xpectr::set_test_seed(42)
  # Assigning output
  output_17365 <- closest_to(data = df, col = "A", origin = 2, origin_fn = NULL, shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_17365),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_17365[["index"]],
    c(3, 6, 4, 5, 2, 1),
    tolerance = 1e-4)
  expect_equal(
    output_17365[["A"]],
    c(2, 1, 3, 4, 5, 6),
    tolerance = 1e-4)
  expect_equal(
    output_17365[["B"]],
    c(0.65699, 0.71911, 0.70506, 0.45774, 0.13467, 0.73659),
    tolerance = 1e-4)
  expect_equal(
    output_17365[["C"]],
    c("C", "F", "D", "E", "B", "A"),
    fixed = TRUE)
  expect_equal(
    output_17365[["G"]],
    c(1, 2, 2, 2, 1, 1),
    tolerance = 1e-4)
  expect_equal(
    output_17365[["G_index"]],
    c(3, 3, 1, 2, 2, 1),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_17365),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_17365),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_17365),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_17365),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_17365)),
    character(0),
    fixed = TRUE)

  # Testing closest_to(data = df, col = "B", origin = 2,...
  # Changed from baseline: col = "B"
  xpectr::set_test_seed(42)
  # Assigning output
  output_11346 <- closest_to(data = df, col = "B", origin = 2, origin_fn = NULL, shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_11346),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_11346[["index"]],
    c(1, 6, 4, 3, 5, 2),
    tolerance = 1e-4)
  expect_equal(
    output_11346[["A"]],
    c(6, 1, 3, 2, 4, 5),
    tolerance = 1e-4)
  expect_equal(
    output_11346[["B"]],
    c(0.73659, 0.71911, 0.70506, 0.65699, 0.45774, 0.13467),
    tolerance = 1e-4)
  expect_equal(
    output_11346[["C"]],
    c("A", "F", "D", "C", "E", "B"),
    fixed = TRUE)
  expect_equal(
    output_11346[["G"]],
    c(1, 2, 2, 1, 2, 1),
    tolerance = 1e-4)
  expect_equal(
    output_11346[["G_index"]],
    c(1, 3, 1, 3, 2, 2),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_11346),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_11346),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_11346),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_11346),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_11346)),
    character(0),
    fixed = TRUE)

  # Testing closest_to(data = df, col = "C", origin = 2,...
  # Changed from baseline: col = "C"
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_16569 <- xpectr::capture_side_effects(closest_to(data = df, col = "C", origin = 2, origin_fn = NULL, shuffle_ties = FALSE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_16569[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable ''col(s)' columns': May only contain the following types: {numeric,factor}, but element 1\n * has type 'character'."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_16569[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing closest_to(data = df, col = NULL, origin = f...
  # Changed from baseline: origin = factor(c(1))
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_17050 <- xpectr::capture_side_effects(closest_to(data = df, col = NULL, origin = factor(c(1)), origin_fn = NULL, shuffle_ties = FALSE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_17050[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'origin': Must be of type 'number' (or 'NULL'), not 'factor'."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_17050[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing closest_to(data = df, col = NULL, origin = 1...
  # Changed from baseline: origin = 10
  xpectr::set_test_seed(42)
  # Assigning output
  output_14577 <- closest_to(data = df, col = NULL, origin = 10, origin_fn = NULL, shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_14577),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_14577[["index"]],
    c(6, 5, 4, 3, 2, 1),
    tolerance = 1e-4)
  expect_equal(
    output_14577[["A"]],
    c(1, 4, 3, 2, 5, 6),
    tolerance = 1e-4)
  expect_equal(
    output_14577[["B"]],
    c(0.71911, 0.45774, 0.70506, 0.65699, 0.13467, 0.73659),
    tolerance = 1e-4)
  expect_equal(
    output_14577[["C"]],
    c("F", "E", "D", "C", "B", "A"),
    fixed = TRUE)
  expect_equal(
    output_14577[["G"]],
    c(2, 2, 2, 1, 1, 1),
    tolerance = 1e-4)
  expect_equal(
    output_14577[["G_index"]],
    c(3, 2, 1, 3, 2, 1),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_14577),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_14577),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_14577),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_14577),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_14577)),
    character(0),
    fixed = TRUE)

  # Testing closest_to(data = df, col = NULL, origin = N...
  # Changed from baseline: origin = NA
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_17191 <- xpectr::capture_side_effects(closest_to(data = df, col = NULL, origin = NA, origin_fn = NULL, shuffle_ties = FALSE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_17191[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'origin': May not be NA."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_17191[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing closest_to(data = df, col = NULL, origin = N...
  # Changed from baseline: origin = NULL
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19346 <- xpectr::capture_side_effects(closest_to(data = df, col = NULL, origin = NULL, origin_fn = NULL, shuffle_ties = FALSE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19346[['error']]),
    xpectr::strip("1 assertions failed:\n * exactly one of {origin,origin_fn} should specified."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19346[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing closest_to(data = df, col = NULL, origin = N...
  # Changed from baseline: origin, origin_fn
  xpectr::set_test_seed(42)
  # Assigning output
  output_12554 <- closest_to(data = df, col = NULL, origin = NULL, origin_fn = create_origin_fn(median), shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_12554),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_12554[["index"]],
    c(3, 4, 2, 5, 1, 6),
    tolerance = 1e-4)
  expect_equal(
    output_12554[["A"]],
    c(2, 3, 5, 4, 6, 1),
    tolerance = 1e-4)
  expect_equal(
    output_12554[["B"]],
    c(0.65699, 0.70506, 0.13467, 0.45774, 0.73659, 0.71911),
    tolerance = 1e-4)
  expect_equal(
    output_12554[["C"]],
    c("C", "D", "B", "E", "A", "F"),
    fixed = TRUE)
  expect_equal(
    output_12554[["G"]],
    c(1, 2, 1, 2, 1, 2),
    tolerance = 1e-4)
  expect_equal(
    output_12554[["G_index"]],
    c(3, 1, 2, 2, 1, 3),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_12554),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_12554),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_12554),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_12554),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_12554)),
    character(0),
    fixed = TRUE)

  # Testing closest_to(data = df, col = NULL, origin = N...
  # Changed from baseline: origin, origin_fn
  xpectr::set_test_seed(42)
  # Assigning output
  output_14622 <- closest_to(data = df, col = NULL, origin = NULL, origin_fn = create_origin_fn(max), shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_14622),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_14622[["index"]],
    c(6, 5, 4, 3, 2, 1),
    tolerance = 1e-4)
  expect_equal(
    output_14622[["A"]],
    c(1, 4, 3, 2, 5, 6),
    tolerance = 1e-4)
  expect_equal(
    output_14622[["B"]],
    c(0.71911, 0.45774, 0.70506, 0.65699, 0.13467, 0.73659),
    tolerance = 1e-4)
  expect_equal(
    output_14622[["C"]],
    c("F", "E", "D", "C", "B", "A"),
    fixed = TRUE)
  expect_equal(
    output_14622[["G"]],
    c(2, 2, 2, 1, 1, 1),
    tolerance = 1e-4)
  expect_equal(
    output_14622[["G_index"]],
    c(3, 2, 1, 3, 2, 1),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_14622),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_14622),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_14622),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_14622),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_14622)),
    character(0),
    fixed = TRUE)

  # Testing closest_to(data = df, col = NULL, origin = N...
  # Changed from baseline: origin, origin_fn
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19400 <- xpectr::capture_side_effects(closest_to(data = df, col = NULL, origin = NULL, origin_fn = create_origin_fn(identity), shuffle_ties = FALSE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19400[['error']]),
    xpectr::strip("output of 'origin_fn' must have same length as 'cols' (1) but had length 6."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19400[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing closest_to(data = df, col = NULL, origin = 2...
  # Changed from baseline: shuffle_ties = TRUE
  xpectr::set_test_seed(42)
  # Assigning output
  output_19782 <- closest_to(data = df, col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = TRUE)
  # Testing class
  expect_equal(
    class(output_19782),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_19782[["index"]],
    c(2, 3, 1, 4, 5, 6),
    tolerance = 1e-4)
  expect_equal(
    output_19782[["A"]],
    c(5, 2, 6, 3, 4, 1),
    tolerance = 1e-4)
  expect_equal(
    output_19782[["B"]],
    c(0.13467, 0.65699, 0.73659, 0.70506, 0.45774, 0.71911),
    tolerance = 1e-4)
  expect_equal(
    output_19782[["C"]],
    c("B", "C", "A", "D", "E", "F"),
    fixed = TRUE)
  expect_equal(
    output_19782[["G"]],
    c(1, 1, 1, 2, 2, 2),
    tolerance = 1e-4)
  expect_equal(
    output_19782[["G_index"]],
    c(2, 3, 1, 1, 2, 3),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_19782),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_19782),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_19782),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_19782),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_19782)),
    character(0),
    fixed = TRUE)

  # Testing closest_to(data = df, col = NULL, origin = 2...
  # Changed from baseline: shuffle_ties = NULL
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_11174 <- xpectr::capture_side_effects(closest_to(data = df, col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = NULL), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_11174[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'shuffle_ties': Must be of type 'logical flag', not 'NULL'."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_11174[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  ## Finished testing 'closest_to'                                            ####
  #

})

test_that("fuzz testing furthest_from()", {
  xpectr::set_test_seed(42)

  # Create a data frame
  df_length <- 6
  df <- data.frame(
    "index" = 1:df_length,
    "A" = sample(1:df_length),
    "B" = runif(df_length),
    "C" = LETTERS[1:df_length],
    "G" = rep(c(1, 2), each = df_length/2),
    "G_index" = rep(1:(df_length/2), times = 2),
    stringsAsFactors = FALSE
  )

  # Generate expectations for 'furthest_from'
  # Tip: comment out the gxs_function() call
  # so it is easy to regenerate the tests
  xpectr::set_test_seed(42)
  # xpectr::gxs_function(
  #   fn = furthest_from,
  #   args_values = list(
  #     "data" = list(df, dplyr::group_by(df, G), 1:10, -3:3, NA),
  #     "col" = list(NULL, "A", "B", "C"),
  #     "origin" = list(2, 10, NA, factor(c(1))),
  #     "origin_fn" = list(NULL),
  #     "shuffle_ties" = list(FALSE, TRUE)
  #   ),
  #   extra_combinations = list(
  #     list("origin" = NULL, "origin_fn" = create_origin_fn(median)),
  #     list("origin" = NULL, "origin_fn" = create_origin_fn(max) ),
  #     list("origin" = NULL, "origin_fn" = create_origin_fn(identity))
  #   ),
  #   indentation = 2
  # )


  ## Testing 'furthest_from'                                                  ####
  ## Initially generated by xpectr
  # Testing different combinations of argument values

  # Testing furthest_from(data = df, col = NULL, origin ...
  xpectr::set_test_seed(42)
  # Assigning output
  output_19148 <- furthest_from(data = df, col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_19148),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_19148[["index"]],
    c(6, 5, 4, 1, 3, 2),
    tolerance = 1e-4)
  expect_equal(
    output_19148[["A"]],
    c(1, 4, 3, 6, 2, 5),
    tolerance = 1e-4)
  expect_equal(
    output_19148[["B"]],
    c(0.71911, 0.45774, 0.70506, 0.73659, 0.65699, 0.13467),
    tolerance = 1e-4)
  expect_equal(
    output_19148[["C"]],
    c("F", "E", "D", "A", "C", "B"),
    fixed = TRUE)
  expect_equal(
    output_19148[["G"]],
    c(2, 2, 2, 1, 1, 1),
    tolerance = 1e-4)
  expect_equal(
    output_19148[["G_index"]],
    c(3, 2, 1, 1, 3, 2),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_19148),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_19148),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_19148),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_19148),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_19148)),
    character(0),
    fixed = TRUE)

  # Testing furthest_from(data = dplyr::group_by(df, G),...
  # Changed from baseline: data = dplyr::group_b...
  xpectr::set_test_seed(42)
  # Assigning output
  output_19370 <- furthest_from(data = dplyr::group_by(df, G), col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_19370),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_19370[["index"]],
    c(1, 3, 2, 4, 6, 5),
    tolerance = 1e-4)
  expect_equal(
    output_19370[["A"]],
    c(6, 2, 5, 3, 1, 4),
    tolerance = 1e-4)
  expect_equal(
    output_19370[["B"]],
    c(0.73659, 0.65699, 0.13467, 0.70506, 0.71911, 0.45774),
    tolerance = 1e-4)
  expect_equal(
    output_19370[["C"]],
    c("A", "C", "B", "D", "F", "E"),
    fixed = TRUE)
  expect_equal(
    output_19370[["G"]],
    c(1, 1, 1, 2, 2, 2),
    tolerance = 1e-4)
  expect_equal(
    output_19370[["G_index"]],
    c(1, 3, 2, 1, 3, 2),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_19370),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_19370),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_19370),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_19370),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_19370)),
    character(0),
    fixed = TRUE)

  # Testing furthest_from(data = 1:10, col = NULL, origi...
  # Changed from baseline: data = 1:10
  xpectr::set_test_seed(42)
  # Assigning output
  output_12861 <- furthest_from(data = 1:10, col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_12861),
    "integer",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_12861,
    type = "integer")
  # Testing values
  expect_equal(
    output_12861,
    c(10, 9, 8, 7, 6, 5, 4, 1, 3, 2),
    tolerance = 1e-4)
  # Testing names
  expect_equal(
    names(output_12861),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_12861),
    10L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_12861)),
    10L)

  # Testing furthest_from(data = -3:3, col = NULL, origi...
  # Changed from baseline: data = -3:3
  xpectr::set_test_seed(42)
  # Assigning output
  output_18304 <- furthest_from(data = -3:3, col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_18304),
    "integer",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_18304,
    type = "integer")
  # Testing values
  expect_equal(
    output_18304,
    c(-3, -2, -1, 0, 1, 3, 2),
    tolerance = 1e-4)
  # Testing names
  expect_equal(
    names(output_18304),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_18304),
    7L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_18304)),
    7L)

  # Testing furthest_from(data = NA, col = NULL, origin ...
  # Changed from baseline: data = NA
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_16417 <- xpectr::capture_side_effects(furthest_from(data = NA, col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = FALSE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_16417[['error']]),
    xpectr::strip("Assertion failed. One of the following must apply:\n * checkmate::check_data_frame(data): Must be of type 'data.frame', not 'logical'\n * checkmate::check_vector(data): Contains missing values (element 1)\n * checkmate::check_factor(data): Contains missing values (element 1)"),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_16417[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing furthest_from(data = NULL, col = NULL, origi...
  # Changed from baseline: data = NULL
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_15190 <- xpectr::capture_side_effects(furthest_from(data = NULL, col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = FALSE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_15190[['error']]),
    xpectr::strip("Assertion failed. One of the following must apply:\n * checkmate::check_data_frame(data): Must be of type 'data.frame', not 'NULL'\n * checkmate::check_vector(data): Must be of type 'vector', not 'NULL'\n * checkmate::check_factor(data): Must be of type 'factor', not 'NULL'"),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_15190[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing furthest_from(data = df, col = "A", origin =...
  # Changed from baseline: col = "A"
  xpectr::set_test_seed(42)
  # Assigning output
  output_17365 <- furthest_from(data = df, col = "A", origin = 2, origin_fn = NULL, shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_17365),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_17365[["index"]],
    c(1, 2, 5, 6, 4, 3),
    tolerance = 1e-4)
  expect_equal(
    output_17365[["A"]],
    c(6, 5, 4, 1, 3, 2),
    tolerance = 1e-4)
  expect_equal(
    output_17365[["B"]],
    c(0.73659, 0.13467, 0.45774, 0.71911, 0.70506, 0.65699),
    tolerance = 1e-4)
  expect_equal(
    output_17365[["C"]],
    c("A", "B", "E", "F", "D", "C"),
    fixed = TRUE)
  expect_equal(
    output_17365[["G"]],
    c(1, 1, 2, 2, 2, 1),
    tolerance = 1e-4)
  expect_equal(
    output_17365[["G_index"]],
    c(1, 2, 2, 3, 1, 3),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_17365),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_17365),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_17365),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_17365),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_17365)),
    character(0),
    fixed = TRUE)

  # Testing furthest_from(data = df, col = "B", origin =...
  # Changed from baseline: col = "B"
  xpectr::set_test_seed(42)
  # Assigning output
  output_11346 <- furthest_from(data = df, col = "B", origin = 2, origin_fn = NULL, shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_11346),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_11346[["index"]],
    c(2, 5, 3, 4, 6, 1),
    tolerance = 1e-4)
  expect_equal(
    output_11346[["A"]],
    c(5, 4, 2, 3, 1, 6),
    tolerance = 1e-4)
  expect_equal(
    output_11346[["B"]],
    c(0.13467, 0.45774, 0.65699, 0.70506, 0.71911, 0.73659),
    tolerance = 1e-4)
  expect_equal(
    output_11346[["C"]],
    c("B", "E", "C", "D", "F", "A"),
    fixed = TRUE)
  expect_equal(
    output_11346[["G"]],
    c(1, 2, 1, 2, 2, 1),
    tolerance = 1e-4)
  expect_equal(
    output_11346[["G_index"]],
    c(2, 2, 3, 1, 3, 1),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_11346),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_11346),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_11346),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_11346),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_11346)),
    character(0),
    fixed = TRUE)

  # Testing furthest_from(data = df, col = "C", origin =...
  # Changed from baseline: col = "C"
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_16569 <- xpectr::capture_side_effects(furthest_from(data = df, col = "C", origin = 2, origin_fn = NULL, shuffle_ties = FALSE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_16569[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable ''col(s)' columns': May only contain the following types: {numeric,factor}, but element 1\n * has type 'character'."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_16569[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing furthest_from(data = df, col = NULL, origin ...
  # Changed from baseline: origin = factor(c(1))
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_17050 <- xpectr::capture_side_effects(furthest_from(data = df, col = NULL, origin = factor(c(1)), origin_fn = NULL, shuffle_ties = FALSE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_17050[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'origin': Must be of type 'number' (or 'NULL'), not 'factor'."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_17050[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing furthest_from(data = df, col = NULL, origin ...
  # Changed from baseline: origin = 10
  xpectr::set_test_seed(42)
  # Assigning output
  output_14577 <- furthest_from(data = df, col = NULL, origin = 10, origin_fn = NULL, shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_14577),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_14577[["index"]],
    c(1, 2, 3, 4, 5, 6),
    tolerance = 1e-4)
  expect_equal(
    output_14577[["A"]],
    c(6, 5, 2, 3, 4, 1),
    tolerance = 1e-4)
  expect_equal(
    output_14577[["B"]],
    c(0.73659, 0.13467, 0.65699, 0.70506, 0.45774, 0.71911),
    tolerance = 1e-4)
  expect_equal(
    output_14577[["C"]],
    c("A", "B", "C", "D", "E", "F"),
    fixed = TRUE)
  expect_equal(
    output_14577[["G"]],
    c(1, 1, 1, 2, 2, 2),
    tolerance = 1e-4)
  expect_equal(
    output_14577[["G_index"]],
    c(1, 2, 3, 1, 2, 3),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_14577),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_14577),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_14577),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_14577),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_14577)),
    character(0),
    fixed = TRUE)

  # Testing furthest_from(data = df, col = NULL, origin ...
  # Changed from baseline: origin = NA
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_17191 <- xpectr::capture_side_effects(furthest_from(data = df, col = NULL, origin = NA, origin_fn = NULL, shuffle_ties = FALSE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_17191[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'origin': May not be NA."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_17191[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing furthest_from(data = df, col = NULL, origin ...
  # Changed from baseline: origin = NULL
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19346 <- xpectr::capture_side_effects(furthest_from(data = df, col = NULL, origin = NULL, origin_fn = NULL, shuffle_ties = FALSE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19346[['error']]),
    xpectr::strip("1 assertions failed:\n * exactly one of {origin,origin_fn} should specified."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19346[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing furthest_from(data = df, col = NULL, origin ...
  # Changed from baseline: origin, origin_fn
  xpectr::set_test_seed(42)
  # Assigning output
  output_12554 <- furthest_from(data = df, col = NULL, origin = NULL, origin_fn = create_origin_fn(median), shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_12554),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_12554[["index"]],
    c(1, 6, 2, 5, 3, 4),
    tolerance = 1e-4)
  expect_equal(
    output_12554[["A"]],
    c(6, 1, 5, 4, 2, 3),
    tolerance = 1e-4)
  expect_equal(
    output_12554[["B"]],
    c(0.73659, 0.71911, 0.13467, 0.45774, 0.65699, 0.70506),
    tolerance = 1e-4)
  expect_equal(
    output_12554[["C"]],
    c("A", "F", "B", "E", "C", "D"),
    fixed = TRUE)
  expect_equal(
    output_12554[["G"]],
    c(1, 2, 1, 2, 1, 2),
    tolerance = 1e-4)
  expect_equal(
    output_12554[["G_index"]],
    c(1, 3, 2, 2, 3, 1),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_12554),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_12554),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_12554),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_12554),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_12554)),
    character(0),
    fixed = TRUE)

  # Testing furthest_from(data = df, col = NULL, origin ...
  # Changed from baseline: origin, origin_fn
  xpectr::set_test_seed(42)
  # Assigning output
  output_14622 <- furthest_from(data = df, col = NULL, origin = NULL, origin_fn = create_origin_fn(max), shuffle_ties = FALSE)
  # Testing class
  expect_equal(
    class(output_14622),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_14622[["index"]],
    c(1, 2, 3, 4, 5, 6),
    tolerance = 1e-4)
  expect_equal(
    output_14622[["A"]],
    c(6, 5, 2, 3, 4, 1),
    tolerance = 1e-4)
  expect_equal(
    output_14622[["B"]],
    c(0.73659, 0.13467, 0.65699, 0.70506, 0.45774, 0.71911),
    tolerance = 1e-4)
  expect_equal(
    output_14622[["C"]],
    c("A", "B", "C", "D", "E", "F"),
    fixed = TRUE)
  expect_equal(
    output_14622[["G"]],
    c(1, 1, 1, 2, 2, 2),
    tolerance = 1e-4)
  expect_equal(
    output_14622[["G_index"]],
    c(1, 2, 3, 1, 2, 3),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_14622),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_14622),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_14622),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_14622),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_14622)),
    character(0),
    fixed = TRUE)

  # Testing furthest_from(data = df, col = NULL, origin ...
  # Changed from baseline: origin, origin_fn
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19400 <- xpectr::capture_side_effects(furthest_from(data = df, col = NULL, origin = NULL, origin_fn = create_origin_fn(identity), shuffle_ties = FALSE), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19400[['error']]),
    xpectr::strip("output of 'origin_fn' must have same length as 'cols' (1) but had length 6."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19400[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  # Testing furthest_from(data = df, col = NULL, origin ...
  # Changed from baseline: shuffle_ties = TRUE
  xpectr::set_test_seed(42)
  # Assigning output
  output_19782 <- furthest_from(data = df, col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = TRUE)
  # Testing class
  expect_equal(
    class(output_19782),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_19782[["index"]],
    c(6, 5, 4, 3, 1, 2),
    tolerance = 1e-4)
  expect_equal(
    output_19782[["A"]],
    c(1, 4, 3, 2, 6, 5),
    tolerance = 1e-4)
  expect_equal(
    output_19782[["B"]],
    c(0.71911, 0.45774, 0.70506, 0.65699, 0.73659, 0.13467),
    tolerance = 1e-4)
  expect_equal(
    output_19782[["C"]],
    c("F", "E", "D", "C", "A", "B"),
    fixed = TRUE)
  expect_equal(
    output_19782[["G"]],
    c(2, 2, 2, 1, 1, 1),
    tolerance = 1e-4)
  expect_equal(
    output_19782[["G_index"]],
    c(3, 2, 1, 3, 1, 2),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_19782),
    c("index", "A", "B", "C", "G", "G_index"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_19782),
    c("integer", "integer", "numeric", "character", "numeric", "integer"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_19782),
    c("integer", "integer", "double", "character", "double", "integer"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_19782),
    c(6L, 6L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_19782)),
    character(0),
    fixed = TRUE)

  # Testing furthest_from(data = df, col = NULL, origin ...
  # Changed from baseline: shuffle_ties = NULL
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_11174 <- xpectr::capture_side_effects(furthest_from(data = df, col = NULL, origin = 2, origin_fn = NULL, shuffle_ties = NULL), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_11174[['error']]),
    xpectr::strip("1 assertions failed:\n * Variable 'shuffle_ties': Must be of type 'logical flag', not 'NULL'."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_11174[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)

  ## Finished testing 'furthest_from'                                         ####
  #

})
