library(rearrr)
context("Pipeline")


test_that("testing printing ByGroupPipeline", {
  xpectr::set_test_seed(42)

  # Idea for example:
  agp <- ByGroupPipeline$new(3)
  agp$add_transformation(
    fn = rotate_2d,
    args = list(
      x_col = "Index",
      y_col = "A",
      origin = c(0, 0),
      suffix = "",
      overwrite = TRUE
    ),
    var_args = list(degrees = list(45, 90, 120)),
    name = "rotate"
  )
  agp$add_transformation(
    fn = cluster_groups,
    args = list(
      cols = c("Index", "A"),
      suffix = "",
      overwrite = TRUE,
      scale_min_fn = function(x){ # For testing shortening in print()
        min(x)+min(x)^2
      }
    ),
    var_args = list(multiplier = list(0.05, 0.1, 0.2)),
    name = "cluster"
  )


  ## Testing 'testthat::capture_output(print(agp))'                         ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Assigning output
  output_19148 <- testthat::capture_output(print(agp))
  # Testing class
  expect_equal(
    class(output_19148),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_19148,
    type = "character")
  # Testing values
  expect_equal(
    output_19148,
    "ByGroupPipeline: \n  No. expected groups: 3\n  rotate\n    Constant Arguments:  x_col=\"Index\", y_col=\"A\", origin=c(0, 0), suffix=\"\", overwrite=TRUE\n    Varying Arguments:   degrees=list(45, 90, 120)\n  cluster\n    Constant Arguments:  cols=c(\"Index\", \"A\"), suffix=\"\", overwrite=TRUE, scale_min_fn=function (x) { min(x...\n    Varying Arguments:   multiplier=list(0.05, 0.1, 0.2)",
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_19148),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_19148),
    1L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_19148)),
    1L)
  ## Finished testing 'testthat::capture_output(print(agp))'                ####

})

test_that("testing printing Pipeline", {
  xpectr::set_test_seed(42)

  # Idea for example:
  pipe <- Pipeline$new()
  pipe$add_transformation(
    fn = rotate_2d,
    args = list(
      x_col = "Index",
      y_col = "A",
      origin = c(0, 0),
      degrees = 45,
      suffix = "",
      overwrite = TRUE
    ),
    name = "rotate"
  )
  pipe$add_transformation(
    fn = cluster_groups,
    args = list(
      cols = c("Index", "A"),
      suffix = "",
      overwrite = TRUE,
      multiplier = 0.05,
      scale_min_fn = function(x){ # For testing shortening in print()
        min(x)+min(x)^2
      }
    ),
    name = "cluster"
  )


  ## Testing 'testthat::capture_output(print(pipe))'                        ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Assigning output
  output_11346 <- testthat::capture_output(print(pipe))
  # Testing class
  expect_equal(
    class(output_11346),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_11346,
    type = "character")
  # Testing values
  expect_equal(
    output_11346,
    "Pipeline: \n  rotate\n    Arguments:  x_col=\"Index\", y_col=\"A\", origin=c(0, 0), degrees=45, suffix=\"\", overwrite=TRUE\n  cluster\n    Arguments:  cols=c(\"Index\", \"A\"), suffix=\"\", overwrite=TRUE, multiplier=0.05, scale_min_fn=function (x) { min(x...",
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_11346),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_11346),
    1L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_11346)),
    1L)
  ## Finished testing 'testthat::capture_output(print(pipe))'               ####


})
